version: '3.8'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: lottery-backend
    restart: always
    networks:
      - portainer_default
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PORT=4000
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=portainer_default"
      - "traefik.http.routers.lottery-backend.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.lottery-backend.priority=10" # Adicionando prioridade
      - "traefik.http.services.lottery-backend.loadbalancer.server.port=4000"
      - "traefik.http.routers.lottery-backend.entrypoints=websecure"
      - "traefik.http.routers.lottery-backend.tls=true"
      - "traefik.http.routers.lottery-backend.tls.certresolver=leresolver"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.lottery-backend.middlewares=api-strip@docker"

    
      # Configuração principal do frontend
      - "traefik.http.routers.lottery-front.rule=Host(`facilitaloterias.com.br`)"
      - "traefik.http.services.lottery-front.loadbalancer.server.port=80" # Change the port to 80
      - "traefik.http.routers.lottery-front.entrypoints=websecure"
      - "traefik.http.routers.lottery-front.tls=true"
      - "traefik.http.routers.lottery-front.tls.certresolver=leresolver"

      # CORS e Middleware para o SPA principal
      - "traefik.http.middlewares.spa.headers.customResponseHeaders.Cache-Control=no-store"
      - "traefik.http.middlewares.spa.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.spa.headers.customResponseHeaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.spa.headers.customResponseHeaders.Access-Control-Allow-Methods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.spa.headers.customResponseHeaders.Access-Control-Allow-Headers=Origin,Content-Type,Accept,Authorization"

      # Middleware para SPA com fallback para index.html
      - "traefik.http.middlewares.spa-fallback.replacepath.path=/"

      # Combinando middlewares
      - "traefik.http.middlewares.spa-chain.chain.middlewares=spa,spa-fallback"
      - "traefik.http.routers.lottery-front.middlewares=spa-chain@docker"

      # Rota específica para mega-sena
      - "traefik.http.routers.lottery-mega-sena.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/mega-sena`)"
      - "traefik.http.routers.lottery-mega-sena.service=lottery-front"
      - "traefik.http.routers.lottery-mega-sena.tls=true"
      - "traefik.http.routers.lottery-mega-sena.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-mega-sena.middlewares=spa-chain@docker"

      # Rota específica para lotofacil
      - "traefik.http.routers.lottery-lotofacil.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/lotofacil`)"
      - "traefik.http.routers.lottery-lotofacil.service=lottery-front"
      - "traefik.http.routers.lottery-lotofacil.tls=true"
      - "traefik.http.routers.lottery-lotofacil.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-lotofacil.middlewares=spa-chain@docker"

      # Rota específica para timemania
      - "traefik.http.routers.lottery-timemania.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/timemania`)"
      - "traefik.http.routers.lottery-timemania.service=lottery-front"
      - "traefik.http.routers.lottery-timemania.tls=true"
      - "traefik.http.routers.lottery-timemania.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-timemania.middlewares=spa-chain@docker"

      # Rota específica para lotomania
      - "traefik.http.routers.lottery-lotomania.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/lotomania`)"
      - "traefik.http.routers.lottery-lotomania.service=lottery-front"
      - "traefik.http.routers.lottery-lotomania.tls=true"
      - "traefik.http.routers.lottery-lotomania.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-lotomania.middlewares=spa-chain@docker"

      # Rota específica para quina
      - "traefik.http.routers.lottery-quina.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/quina`)"
      - "traefik.http.routers.lottery-quina.service=lottery-front"
      - "traefik.http.routers.lottery-quina.tls=true"
      - "traefik.http.routers.lottery-quina.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-quina.middlewares=spa-chain@docker"

      # Rota específica para mais-milionaria
      - "traefik.http.routers.lottery-mais-milionaria.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/mais-milionaria`)"
      - "traefik.http.routers.lottery-mais-milionaria.service=lottery-front"
      - "traefik.http.routers.lottery-mais-milionaria.tls=true"
      - "traefik.http.routers.lottery-mais-milionaria.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-mais-milionaria.middlewares=spa-chain@docker"

      # Rota específica para dia-de-sorte
      - "traefik.http.routers.lottery-dia-de-sorte.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/dia-de-sorte`)"
      - "traefik.http.routers.lottery-dia-de-sorte.service=lottery-front"
      - "traefik.http.routers.lottery-dia-de-sorte.tls=true"
      - "traefik.http.routers.lottery-dia-de-sorte.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-dia-de-sorte.middlewares=spa-chain@docker"

      # Rota específica para dupla-sena
      - "traefik.http.routers.lottery-dupla-sena.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/dupla-sena`)"
      - "traefik.http.routers.lottery-dupla-sena.service=lottery-front"
      - "traefik.http.routers.lottery-dupla-sena.tls=true"
      - "traefik.http.routers.lottery-dupla-sena.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-dupla-sena.middlewares=spa-chain@docker"

      # Rota específica para super-sete
      - "traefik.http.routers.lottery-supersete.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/supersete`)"
      - "traefik.http.routers.lottery-supersete.service=lottery-front"
      - "traefik.http.routers.lottery-supersete.tls=true"
      - "traefik.http.routers.lottery-supersete.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-supersete.middlewares=spa-chain@docker"

      # Static assets configuration
      - "traefik.http.routers.lottery-assets.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/assets`)"
      - "traefik.http.routers.lottery-assets.service=lottery-front"
      - "traefik.http.routers.lottery-assets.tls=true"
      - "traefik.http.routers.lottery-assets.tls.certresolver=leresolver"
      - "traefik.http.routers.lottery-assets.middlewares=spa@docker"
    
  # Serviço dedicado para servir imagens
  images:
    image: nginx:alpine
    container_name: lottery-images
    restart: always
    networks:   
      - portainer_default
    volumes:
      - /root/.local/share/src/assets/img:/usr/share/nginx/html/images:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=portainer_default"
      - "traefik.http.routers.lottery-static-images.rule=Host(`facilitaloterias.com.br`) && PathPrefix(`/images`)"
      - "traefik.http.services.lottery-static-images.loadbalancer.server.port=80"
      - "traefik.http.routers.lottery-static-images.entrypoints=websecure"
      - "traefik.http.routers.lottery-static-images.tls=true"
      - "traefik.http.routers.lottery-static-images.tls.certresolver=leresolver"
      - "traefik.http.middlewares.images-headers.headers.customResponseHeaders.Cache-Control=public,max-age=86400"
      - "traefik.http.middlewares.images-headers.headers.customResponseHeaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.images-headers.headers.customResponseHeaders.Content-Type=image/png, image/jpeg, image/gif, image/webp"
      - "traefik.http.routers.lottery-static-images.middlewares=images-headers@docker"

      # Middleware para imagens
      - "traefik.http.middlewares.images-headers.headers.customResponseHeaders.Cache-Control=public,max-age=86400"
      - "traefik.http.middlewares.images-headers.headers.customResponseHeaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.images-headers.headers.customResponseHeaders.Content-Type=image/png, image/jpeg, image/gif, image/webp"
   


  
networks:
  portainer_default:
    external: true
  lottery_network:
    driver: bridge

volumes:
  lottery_db_data:
    driver: local
